run:
	srun -p thinnodes -N 2 -t 00:00:10 pingpong -n 4 -iter 8
	#^Zsbatch -p thinnodes ./launcher.sh

clean:
	rm -rf a.out main pingpong slurm*

all:
	mpicc main.cpp -o main
	mpicc pingpong.c -o pingpong
